"""Initial Migration

Revision ID: ccc924648c1e
Revises: 47b2fe44f124
Create Date: 2020-07-20 20:41:31.063483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc924648c1e'
down_revision = '47b2fe44f124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=255), nullable=True))
    op.drop_column('comments', 'opinion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('opinion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
